spring:
  application:
    name:user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuqi?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400